name: GitHub - Activity - Readme

on:
  schedule:
    - cron: "0 21 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: Starshadow0707/github-activity-readme@v0.4.4  # Correct indentation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
