
# GitHub Action for generating a contribution graph with a snake eating your contributions.
name: Generate Snake

# Controls when the action will run.
on:
  schedule:
      # every 12 hours
    - cron: "0 */12 * * *"

  # This command allows us to run the Action automatically from the Actions tab.
  workflow_dispatch:
  
  # Also run on every push on the master branch
  push:
    branches:
    - main

# The sequence of runs in this workflow:
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
    
      - name: Generate the snake files in './dist/'
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |            
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake-orange-blue.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
            dist/github-contribution-grid-snake-blue-red.gif?color_snake=blue&color_dots=#ff0000,#00ff00,#0000ff
            dist/github-contribution-grid-snake-smooth-rainbow.gif?animation_speed=slow&color_snake=rainbow&color_dots=#ff77ff,#39ff14,#ff5722
            dist/github-contribution-grid-snake-glowing-cyan.gif?animation_speed=medium&color_snake=cyan&color_dots=#e76f51,#264653
            dist/github-contribution-grid-snake-3d-illusion.gif?animation_speed=slow&color_snake=blue&color_dots=#ffd700,#008080
            dist/github-contribution-grid-snake-fast-pulse.gif?animation_speed=fast&color_snake=purple&color_dots=#f4a261,#2a9d8f
            dist/github-contribution-grid-snake-pulse-blue-yellow.gif?animation_speed=medium&color_snake=blue&color_dots=#ff7f00,#ffdd00
            dist/github-contribution-grid-snake-neon-green.gif?color_snake=green&color_dots=#00ff00,#000000
            dist/github-contribution-grid-snake-pastel-colors.gif?color_snake=purple&color_dots=#f1e1f6,#a8d0e6
            dist/github-contribution-grid-snake-psychedelic.gif?animation_speed=fast&color_snake=yellow&color_dots=#e63946,#f1faee,#a8dadc
            dist/github-contribution-grid-snake-animated-pulse.gif?animation_speed=fast&color_snake=red&color_dots=#ff6347,#ff4500
            dist/github-contribution-grid-snake-bubblegum.gif?color_snake=pink&color_dots=#e1bee7,#f48fb1
            dist/github-contribution-grid-snake-electric-blue.gif?color_snake=blue&color_dots=#00bcd4,#03a9f4
            dist/github-contribution-grid-snake-frozen-blue.gif?animation_speed=slow&color_snake=blue&color_dots=#4dd0e1,#0288d1
            dist/github-contribution-grid-snake-cyberpunk.gif?color_snake=magenta&color_dots=#9c27b0,#3f51b5
            dist/github-contribution-grid-snake-glitter-gold.gif?animation_speed=medium&color_snake=gold&color_dots=#ffb300,#ff9800
            dist/github-contribution-grid-snake-rainbow-blast.gif?animation_speed=medium&color_snake=rainbow&color_dots=#ff5733,#33ff57,#5733ff
            dist/github-contribution-grid-snake-aurora.gif?animation_speed=slow&color_snake=cyan&color_dots=#00bcd4,#ffeb3b
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: ensure the generated file exists
        run: |
          ls dist
          test -f dist/github-contribution-grid-snake.svg
          test -f dist/github-contribution-grid-snake-dark.svg
          test -f dist/github-contribution-grid-snake-orange-blue.gif
          test -f dist/github-contribution-grid-snake-blue-red.gif
          test -f dist/github-contribution-grid-snake-smooth-rainbow.gif
          test -f dist/github-contribution-grid-snake-glowing-cyan.gif
          test -f dist/github-contribution-grid-snake-3d-illusion.gif
          test -f dist/github-contribution-grid-snake-fast-pulse.gif
          test -f dist/github-contribution-grid-snake-pulse-blue-yellow.gif
          test -f dist/github-contribution-grid-snake-neon-green.gif
          test -f dist/github-contribution-grid-snake-pastel-colors.gif
          test -f dist/github-contribution-grid-snake-psychedelic.gif
          test -f dist/github-contribution-grid-snake-animated-pulse.gif
          test -f dist/github-contribution-grid-snake-bubblegum.gif
          test -f dist/github-contribution-grid-snake-electric-blue.gif
          test -f dist/github-contribution-grid-snake-frozen-blue.gif
          test -f dist/github-contribution-grid-snake-cyberpunk.gif
          test -f dist/github-contribution-grid-snake-glitter-gold.gif
          test -f dist/github-contribution-grid-snake-rainbow-blast.gif
          test -f dist/github-contribution-grid-snake-aurora.gif

      - name: Show build status
        run: git status

      - name: Push new files to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          commit_message: Update snake animations
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
