name: WakaReadme

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Update WakaReadme
      uses: athul/waka-readme@8539bedb8277066fc9fe1b47d1f9b108eb866494
      with:
        COMMIT_MESSAGE: Update Wakapi stats
        BLOCKS: ⬜🟨🟩
        TIME_RANGE: last_7_days
        SHOW_TIME: true
        SHOW_TITLE: true
        SHOW_TOTAL: true
        API_BASE_URL: https://wakatime.com/api
        REPOSITORY: VoidSon-Stubs/VoidSon-Stubs
        SECTION_NAME: waka
        CODE_LANG: txt
        LANG_COUNT: 5
        SHOW_MASKED_TIME: false
        STOP_AT_OTHER: false
        TARGET_BRANCH: ""  # Leave empty if not used
        TARGET_PATH: ""    # Leave empty if not used
        COMMITTER_NAME: "" # Leave empty if not used
        COMMITTER_EMAIL: "" # Leave empty if not used
        AUTHOR_NAME: ""    # Leave empty if not used
        AUTHOR_EMAIL: ""   # Leave empty if not used
      env:
        WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
